package org.bluepigeon.admin.model;
// Generated 26 Apr, 2017 4:54:07 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AdminUserPhotos generated by hbm2java
 */
@Entity
@Table(name = "admin_user_photos", catalog = "blue_pigeon")
public class AdminUserPhotos implements java.io.Serializable {

	private Integer id;
	private AdminUser adminUser;
	private String photoUrl;

	public AdminUserPhotos() {
	}

	public AdminUserPhotos(AdminUser adminUser, String photoUrl) {
		this.adminUser = adminUser;
		this.photoUrl = photoUrl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "admin_id")
	public AdminUser getAdminUser() {
		return this.adminUser;
	}

	public void setAdminUser(AdminUser adminUser) {
		this.adminUser = adminUser;
	}

	@Column(name = "photo_url", length = 225)
	public String getPhotoUrl() {
		return this.photoUrl;
	}

	public void setPhotoUrl(String photoUrl) {
		this.photoUrl = photoUrl;
	}

}
