package org.bluepigeon.admin.model;
// Generated 7 Apr, 2017 12:35:04 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AgreementInfo generated by hbm2java
 */
@Entity
@Table(name = "agreement_info", catalog = "blue_pigeon")
public class AgreementInfo implements java.io.Serializable {

	private Integer id;
	private Agreement agreement;
	private String docUrl;

	public AgreementInfo() {
	}

	public AgreementInfo(Agreement agreement, String docUrl) {
		this.agreement = agreement;
		this.docUrl = docUrl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "agreement_id")
	public Agreement getAgreement() {
		return this.agreement;
	}

	public void setAgreement(Agreement agreement) {
		this.agreement = agreement;
	}

	@Column(name = "doc_url", length = 225)
	public String getDocUrl() {
		return this.docUrl;
	}

	public void setDocUrl(String docUrl) {
		this.docUrl = docUrl;
	}

}
