package org.bluepigeon.admin.model;
// Generated 27 Mar, 2017 5:55:47 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AreaUnit generated by hbm2java
 */
@Entity
@Table(name = "area_unit", catalog = "blue_pigeon")
public class AreaUnit implements java.io.Serializable {

	private Short id;
	private String name;
	private Double sqft_value;
	private Byte status;
	private Byte isDeleted;
	private Set<BuilderProject> builderProjects = new HashSet<BuilderProject>(0);

	public AreaUnit() {
	}

	public AreaUnit(String name, Byte status, Byte isDeleted, Set<BuilderProject> builderProjects) {
		this.name = name;
		this.status = status;
		this.isDeleted = isDeleted;
		this.builderProjects = builderProjects;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Short getId() {
		return this.id;
	}

	public void setId(Short id) {
		this.id = id;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "sqft_value", precision = 22, scale = 2)
	public Double getSqft_value() {
		return sqft_value;
	}

	public void setSqft_value(Double sqft_value) {
		this.sqft_value = sqft_value;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "is_deleted")
	public Byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "areaUnit")
	public Set<BuilderProject> getBuilderProjects() {
		return this.builderProjects;
	}

	public void setBuilderProjects(Set<BuilderProject> builderProjects) {
		this.builderProjects = builderProjects;
	}

}
