package org.bluepigeon.admin.model;
// Generated 27 Mar, 2017 5:55:47 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BuilderFloor generated by hbm2java
 */
@Entity
@Table(name = "builder_floor", catalog = "blue_pigeon")
public class BuilderFloor implements java.io.Serializable {

	private Integer id;
	private BuilderBuilding builderBuilding;
	private BuilderFloorStatus builderFloorStatus;
	private String name;
	private Integer floorNo;
	private Integer totalFlats;
	private Double completionStatus = 0.0;
	private Double amenityWeightage = 0.0;
	private Double flatWeightage = 0.0;
	private Double weightage = 0.0;
	private Byte status;

	public BuilderFloor() {
	}

	public BuilderFloor(BuilderBuilding builderBuilding, BuilderFloorStatus builderFloorStatus, String name, Double completionStatus,
			Integer floorNo, Integer totalFlats, Byte status, Double amenityWeightage, Double flatWeightage, Double weightage) {
		this.builderBuilding = builderBuilding;
		this.builderFloorStatus = builderFloorStatus;
		this.name = name;
		this.floorNo = floorNo;
		this.totalFlats = totalFlats;
		this.status = status;
		this.completionStatus = completionStatus;
		this.amenityWeightage = amenityWeightage;
		this.flatWeightage = flatWeightage;
		this.weightage = weightage;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "building_id")
	public BuilderBuilding getBuilderBuilding() {
		return builderBuilding;
	}
	public void setBuilderBuilding(BuilderBuilding builderBuilding) {
		this.builderBuilding = builderBuilding;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "status_id")
	public BuilderFloorStatus getBuilderFloorStatus() {
		return this.builderFloorStatus;
	}
	public void setBuilderFloorStatus(BuilderFloorStatus builderFloorStatus) {
		this.builderFloorStatus = builderFloorStatus;
	}
	@Column(name = "name", length = 128)
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	@Column(name = "floor_no")
	public Integer getFloorNo() {
		return floorNo;
	}
	public void setFloorNo(Integer floorNo) {
		this.floorNo = floorNo;
	}

	@Column(name = "total_flats")
	public Integer getTotalFlats() {
		return this.totalFlats;
	}

	public void setTotalFlats(Integer totalFlats) {
		this.totalFlats = totalFlats;
	}
	@Column(name = "status")
	public Byte getStatus() {
		return status;
	}
	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "completion_status", precision = 22, scale = 0)
	public Double getCompletionStatus() {
		return this.completionStatus;
	}

	public void setCompletionStatus(Double completionStatus) {
		this.completionStatus = completionStatus;
	}
	@Column(name = "amenity_weightage", precision = 22, scale = 0)
	public Double getAmenityWeightage() {
		return amenityWeightage;
	}

	public void setAmenityWeightage(Double amenityWeightage) {
		this.amenityWeightage = amenityWeightage;
	}
	@Column(name = "flat_weightage", precision = 22, scale = 0)
	public Double getFlatWeightage() {
		return flatWeightage;
	}

	public void setFlatWeightage(Double flatWeightage) {
		this.flatWeightage = flatWeightage;
	}
	@Column(name = "weightage", precision = 22, scale = 0)
	public Double getWeightage() {
		return weightage;
	}

	public void setWeightage(Double weightage) {
		this.weightage = weightage;
	}

}
