package org.bluepigeon.admin.model;
// Generated 27 Mar, 2017 5:55:47 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BuilderFloorAmenitySubstages generated by hbm2java
 */
@Entity
@Table(name = "builder_floor_amenity_substages", catalog = "blue_pigeon")
public class BuilderFloorAmenitySubstages implements java.io.Serializable {

	private Integer id;
	private BuilderFloorAmenityStages builderFloorAmenityStages;
	private String name;
	private Byte status;

	public BuilderFloorAmenitySubstages() {
	}

	public BuilderFloorAmenitySubstages(BuilderFloorAmenityStages builderFloorAmenityStages, String name, Byte status) {
		this.builderFloorAmenityStages = builderFloorAmenityStages;
		this.name = name;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "stage_id")
	public BuilderFloorAmenityStages getBuilderFloorAmenityStages() {
		return this.builderFloorAmenityStages;
	}

	public void setBuilderFloorAmenityStages(BuilderFloorAmenityStages builderFloorAmenityStages) {
		this.builderFloorAmenityStages = builderFloorAmenityStages;
	}

	@Column(name = "name", length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
