package org.bluepigeon.admin.model;
// Generated 16 Mar, 2017 3:30:20 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BuilderProjectBankInfo generated by hbm2java
 */
@Entity
@Table(name = "builder_project_bank_info", catalog = "blue_pigeon")
public class BuilderProjectBankInfo implements java.io.Serializable {

	private Integer id;
	private BuilderProject builderProject;
	private HomeLoanBanks homeLoanBanks;

	public BuilderProjectBankInfo() {
	}

	public BuilderProjectBankInfo(BuilderProject builderProject, HomeLoanBanks homeLoanBanks) {
		this.builderProject = builderProject;
		this.homeLoanBanks = homeLoanBanks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project_id")
	public BuilderProject getBuilderProject() {
		return this.builderProject;
	}

	public void setBuilderProject(BuilderProject builderProject) {
		this.builderProject = builderProject;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bank_id")
	public HomeLoanBanks getHomeLoanBanks() {
		return this.homeLoanBanks;
	}

	public void setHomeLoanBanks(HomeLoanBanks homeLoanBanks) {
		this.homeLoanBanks = homeLoanBanks;
	}

}
