package org.bluepigeon.admin.model;
// Generated 27 Mar, 2017 5:55:47 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToOne;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BuilderProjectPriceInfo generated by hbm2java
 */
@Entity
@Table(name = "builder_project_price_info", catalog = "blue_pigeon")
public class BuilderProjectPriceInfo implements java.io.Serializable {

	private Integer id;
	private BuilderProject builderProject;
	private Double basePrice;
	private Double riseRate;
	private Integer post;
	private Double amenityRate;
	private Double parking;
	private Double maintenance;
	private Double stampDuty;
	private Integer tenure;
	private Double tax;
	private Double vat;
	private Double fee;
	private AreaUnit areaUnit;

	public BuilderProjectPriceInfo() {
	}

	public BuilderProjectPriceInfo(BuilderProject builderProject, Double basePrice, Double riseRate, Integer post,
			Double amenityRate, Double parking, Double maintenance, Double stampDuty, Integer tenure, Double tax,
			Double vat, Double fee, AreaUnit areaUnit) {
		this.builderProject = builderProject;
		this.basePrice = basePrice;
		this.riseRate = riseRate;
		this.post = post;
		this.amenityRate = amenityRate;
		this.parking = parking;
		this.maintenance = maintenance;
		this.stampDuty = stampDuty;
		this.tenure = tenure;
		this.tax = tax;
		this.vat = vat;
		this.fee = fee;
		this.areaUnit = areaUnit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public BuilderProject getBuilderProject() {
		return this.builderProject;
	}

	public void setBuilderProject(BuilderProject builderProject) {
		this.builderProject = builderProject;
	}

	@Column(name = "base_price", precision = 21, scale = 2)
	public Double getBasePrice() {
		return this.basePrice;
	}

	public void setBasePrice(Double basePrice) {
		this.basePrice = basePrice;
	}

	@Column(name = "rise_rate", precision = 22, scale = 2)
	public Double getRiseRate() {
		return this.riseRate;
	}

	public void setRiseRate(Double riseRate) {
		this.riseRate = riseRate;
	}

	@Column(name = "post")
	public Integer getPost() {
		return this.post;
	}

	public void setPost(Integer post) {
		this.post = post;
	}

	@Column(name = "amenity_rate", precision = 22, scale = 2)
	public Double getAmenityRate() {
		return this.amenityRate;
	}

	public void setAmenityRate(Double amenityRate) {
		this.amenityRate = amenityRate;
	}

	@Column(name = "parking", precision = 22, scale = 2)
	public Double getParking() {
		return this.parking;
	}

	public void setParking(Double parking) {
		this.parking = parking;
	}

	@Column(name = "maintenance", precision = 22, scale = 2)
	public Double getMaintenance() {
		return this.maintenance;
	}

	public void setMaintenance(Double maintenance) {
		this.maintenance = maintenance;
	}

	@Column(name = "stamp_duty", precision = 22, scale = 2)
	public Double getStampDuty() {
		return this.stampDuty;
	}

	public void setStampDuty(Double stampDuty) {
		this.stampDuty = stampDuty;
	}

	@Column(name = "tenure")
	public Integer getTenure() {
		return this.tenure;
	}

	public void setTenure(Integer tenure) {
		this.tenure = tenure;
	}

	@Column(name = "tax", precision = 22, scale = 2)
	public Double getTax() {
		return this.tax;
	}

	public void setTax(Double tax) {
		this.tax = tax;
	}

	@Column(name = "vat", precision = 22, scale = 2)
	public Double getVat() {
		return this.vat;
	}

	public void setVat(Double vat) {
		this.vat = vat;
	}

	@Column(name = "fee", precision = 22, scale = 2)
	public Double getFee() {
		return this.fee;
	}

	public void setFee(Double fee) {
		this.fee = fee;
	}
	
	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "base_unit")
	public AreaUnit getAreaUnit() {
		return this.areaUnit;
	}

	public void setAreaUnit(AreaUnit areaUnit) {
		this.areaUnit = areaUnit;
	}

}
