package org.bluepigeon.admin.model;
// Generated 27 Mar, 2017 5:55:47 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BuilderFloorAmenityStages generated by hbm2java
 */
@Entity
@Table(name = "builder_floor_amenity_stages", catalog = "blue_pigeon")
public class BuilderFloorAmenityStages implements java.io.Serializable {

	private Integer id;
	private BuilderFloorAmenity builderFloorAmenity;
	private String name;
	private Byte status;
	private Set<BuilderFloorAmenitySubstages> builderFloorAmenitySubstageses = new HashSet<BuilderFloorAmenitySubstages>(
			0);

	public BuilderFloorAmenityStages() {
	}

	public BuilderFloorAmenityStages(BuilderFloorAmenity builderFloorAmenity, String name, Byte status,
			Set<BuilderFloorAmenitySubstages> builderFloorAmenitySubstageses) {
		this.builderFloorAmenity = builderFloorAmenity;
		this.name = name;
		this.status = status;
		this.builderFloorAmenitySubstageses = builderFloorAmenitySubstageses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "amenity_id")
	public BuilderFloorAmenity getBuilderFloorAmenity() {
		return this.builderFloorAmenity;
	}

	public void setBuilderFloorAmenity(BuilderFloorAmenity builderFloorAmenity) {
		this.builderFloorAmenity = builderFloorAmenity;
	}

	@Column(name = "name", length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "builderFloorAmenityStages")
	public Set<BuilderFloorAmenitySubstages> getBuilderFloorAmenitySubstageses() {
		return this.builderFloorAmenitySubstageses;
	}

	public void setBuilderFloorAmenitySubstageses(Set<BuilderFloorAmenitySubstages> builderFloorAmenitySubstageses) {
		this.builderFloorAmenitySubstageses = builderFloorAmenitySubstageses;
	}

}
