package org.bluepigeon.admin.model;
// Generated 16 Mar, 2017 3:30:20 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BuilderOverallProjectStagesAndSubStages generated by hbm2java
 */
@Entity
@Table(name = "builder_overall_project_stages_and_sub_stages", catalog = "blue_pigeon")
public class BuilderOverallProjectStagesAndSubStages implements java.io.Serializable {

	private Integer id;
	private String name;
	private Byte status;

	public BuilderOverallProjectStagesAndSubStages() {
	}

	public BuilderOverallProjectStagesAndSubStages(String name, Byte status) {
		this.name = name;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
