package org.bluepigeon.admin.model;
// Generated 28 Mar, 2017 12:04:04 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BuildingPanoramicImage generated by hbm2java
 */
@Entity
@Table(name = "building_panoramic_image", catalog = "blue_pigeon")
public class BuildingPanoramicImage implements java.io.Serializable {

	private Integer id;
	private BuilderBuilding builderBuilding;
	private String title;
	private String panoImage;

	public BuildingPanoramicImage() {
	}

	public BuildingPanoramicImage(BuilderBuilding builderBuilding, String title, String panoImage) {
		this.builderBuilding = builderBuilding;
		this.title = title;
		this.panoImage = panoImage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "building_id")
	public BuilderBuilding getBuilderBuilding() {
		return this.builderBuilding;
	}

	public void setBuilderBuilding(BuilderBuilding builderBuilding) {
		this.builderBuilding = builderBuilding;
	}

	@Column(name = "title", length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "pano_image", length = 128)
	public String getPanoImage() {
		return this.panoImage;
	}

	public void setPanoImage(String panoImage) {
		this.panoImage = panoImage;
	}

}
