package org.bluepigeon.admin.model;
// Generated 23 Mar, 2017 10:55:42 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BuilderProjectAmenity generated by hbm2java
 */
@Entity
@Table(name = "builder_project_amenity", catalog = "blue_pigeon")
public class BuilderProjectAmenity implements java.io.Serializable {

	private Integer id;
	private String name;
	private Byte status;
	private Set<BuilderProjectAmenityStages> builderProjectAmenityStageses = new HashSet<BuilderProjectAmenityStages>(
			0);

	public BuilderProjectAmenity() {
	}

	public BuilderProjectAmenity(String name, Byte status,
			Set<BuilderProjectAmenityStages> builderProjectAmenityStageses) {
		this.name = name;
		this.status = status;
		this.builderProjectAmenityStageses = builderProjectAmenityStageses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "builderProjectAmenity")
	public Set<BuilderProjectAmenityStages> getBuilderProjectAmenityStageses() {
		return this.builderProjectAmenityStageses;
	}

	public void setBuilderProjectAmenityStageses(Set<BuilderProjectAmenityStages> builderProjectAmenityStageses) {
		this.builderProjectAmenityStageses = builderProjectAmenityStageses;
	}

}
