package org.bluepigeon.admin.model;
// Generated 27 Mar, 2017 5:55:47 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BuilderFlatType generated by hbm2java
 */
@Entity
@Table(name = "builder_flat_type", catalog = "blue_pigeon")
public class BuilderFlatType implements java.io.Serializable {

	private Integer id;
	private BuilderBuilding builderBuilding;
	private AdminUser adminUser;
	private BuilderProjectPropertyConfiguration builderProjectPropertyConfiguration;
	private BuilderProject builderProject;
	private String name;
	private Double floorArea;
	private Integer floorUsed;
	private Byte status;
	private Set<BuilderFlat> builderFlats = new HashSet<BuilderFlat>(0);

	public BuilderFlatType() {
	}

	public BuilderFlatType(BuilderBuilding builderBuilding, AdminUser adminUser,
			BuilderProjectPropertyConfiguration builderProjectPropertyConfiguration, BuilderProject builderProject,
			String name, Double floorArea, Integer floorUsed, Byte status,
			Set<BuilderFlat> builderFlats) {
		this.builderBuilding = builderBuilding;
		this.adminUser = adminUser;
		this.builderProjectPropertyConfiguration = builderProjectPropertyConfiguration;
		this.builderProject = builderProject;
		this.name = name;
		this.floorArea = floorArea;
		this.floorUsed = floorUsed;
		this.status = status;
		this.builderFlats = builderFlats;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "building_id")
	public BuilderBuilding getBuilderBuilding() {
		return this.builderBuilding;
	}

	public void setBuilderBuilding(BuilderBuilding builderBuilding) {
		this.builderBuilding = builderBuilding;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "emp_id")
	public AdminUser getAdminUser() {
		return this.adminUser;
	}

	public void setAdminUser(AdminUser adminUser) {
		this.adminUser = adminUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "config_id")
	public BuilderProjectPropertyConfiguration getBuilderProjectPropertyConfiguration() {
		return this.builderProjectPropertyConfiguration;
	}

	public void setBuilderProjectPropertyConfiguration(
			BuilderProjectPropertyConfiguration builderProjectPropertyConfiguration) {
		this.builderProjectPropertyConfiguration = builderProjectPropertyConfiguration;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public BuilderProject getBuilderProject() {
		return this.builderProject;
	}

	public void setBuilderProject(BuilderProject builderProject) {
		this.builderProject = builderProject;
	}

	@Column(name = "name", length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "floor_area")
	public Double getFloorArea() {
		return this.floorArea;
	}

	public void setFloorArea(Double floorArea) {
		this.floorArea = floorArea;
	}

	@Column(name = "floor_used")
	public Integer getFloorUsed() {
		return this.floorUsed;
	}

	public void setFloorUsed(Integer floorUsed) {
		this.floorUsed = floorUsed;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "builderFlatType")
	public Set<BuilderFlat> getBuilderFlats() {
		return this.builderFlats;
	}

	public void setBuilderFlats(Set<BuilderFlat> builderFlats) {
		this.builderFlats = builderFlats;
	}

}
