package org.bluepigeon.admin.model;
// Generated 16 Mar, 2017 3:30:20 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BuilderBuildingAmenitySubstages generated by hbm2java
 */
@Entity
@Table(name = "builder_building_amenity_substages", catalog = "blue_pigeon")
public class BuilderBuildingAmenitySubstages implements java.io.Serializable {

	private Integer id;
	private BuilderBuildingAmenityStages builderBuildingAmenityStages;
	private String name;
	private Byte status;
	private Byte isDeleted;

	public BuilderBuildingAmenitySubstages() {
	}

	public BuilderBuildingAmenitySubstages(BuilderBuildingAmenityStages builderBuildingAmenityStages, String name,
			Byte status, Byte isDeleted) {
		this.builderBuildingAmenityStages = builderBuildingAmenityStages;
		this.name = name;
		this.status = status;
		this.isDeleted = isDeleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "stage_id")
	public BuilderBuildingAmenityStages getBuilderBuildingAmenityStages() {
		return this.builderBuildingAmenityStages;
	}

	public void setBuilderBuildingAmenityStages(BuilderBuildingAmenityStages builderBuildingAmenityStages) {
		this.builderBuildingAmenityStages = builderBuildingAmenityStages;
	}

	@Column(name = "name", length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "is_deleted")
	public Byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Byte isDeleted) {
		this.isDeleted = isDeleted;
	}

}
