package org.bluepigeon.admin.model;
// Generated 20 Mar, 2017 3:36:16 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BuilderProjectOfferInfo generated by hbm2java
 */
@Entity
@Table(name = "builder_project_offer_info", catalog = "blue_pigeon")
public class BuilderProjectOfferInfo implements java.io.Serializable {

	private Integer id;
	private BuilderProject builderProject;
	private String title;
	private Double per;
	private Double amount;
	private Double applicable;
	private Byte apply;

	public BuilderProjectOfferInfo() {
	}

	public BuilderProjectOfferInfo(BuilderProject builderProject, String title, Double per, Double amount,
			Double applicable, Byte apply) {
		this.builderProject = builderProject;
		this.title = title;
		this.per = per;
		this.amount = amount;
		this.applicable = applicable;
		this.apply = apply;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project_id")
	public BuilderProject getBuilderProject() {
		return this.builderProject;
	}

	public void setBuilderProject(BuilderProject builderProject) {
		this.builderProject = builderProject;
	}

	@Column(name = "title", length = 128)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "per", precision = 22, scale = 0)
	public Double getPer() {
		return this.per;
	}

	public void setPer(Double per) {
		this.per = per;
	}

	@Column(name = "amount", precision = 22, scale = 0)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Column(name = "applicable", precision = 22, scale = 0)
	public Double getApplicable() {
		return this.applicable;
	}

	public void setApplicable(Double applicable) {
		this.applicable = applicable;
	}

	@Column(name = "apply")
	public Byte getApply() {
		return this.apply;
	}

	public void setApply(Byte apply) {
		this.apply = apply;
	}

}
