package org.bluepigeon.admin.model;
// Generated 27 Mar, 2017 5:55:47 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BuilderFlatAmenityStages generated by hbm2java
 */
@Entity
@Table(name = "builder_flat_amenity_stages", catalog = "blue_pigeon")
public class BuilderFlatAmenityStages implements java.io.Serializable {

	private Integer id;
	private BuilderFlatAmenity builderFlatAmenity;
	private String name;
	private Byte status;
	private Set<BuilderFlatAmenitySubstages> builderFlatAmenitySubstageses = new HashSet<BuilderFlatAmenitySubstages>(
			0);

	public BuilderFlatAmenityStages() {
	}

	public BuilderFlatAmenityStages(BuilderFlatAmenity builderFlatAmenity, String name, Byte status,
			Set<BuilderFlatAmenitySubstages> builderFlatAmenitySubstageses) {
		this.builderFlatAmenity = builderFlatAmenity;
		this.name = name;
		this.status = status;
		this.builderFlatAmenitySubstageses = builderFlatAmenitySubstageses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "amenity_id")
	public BuilderFlatAmenity getBuilderFlatAmenity() {
		return this.builderFlatAmenity;
	}

	public void setBuilderFlatAmenity(BuilderFlatAmenity builderFlatAmenity) {
		this.builderFlatAmenity = builderFlatAmenity;
	}

	@Column(name = "name", length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "builderFlatAmenityStages")
	public Set<BuilderFlatAmenitySubstages> getBuilderFlatAmenitySubstageses() {
		return this.builderFlatAmenitySubstageses;
	}

	public void setBuilderFlatAmenitySubstageses(Set<BuilderFlatAmenitySubstages> builderFlatAmenitySubstageses) {
		this.builderFlatAmenitySubstageses = builderFlatAmenitySubstageses;
	}

}
