package org.bluepigeon.admin.model;
//Generated 27 Mar, 2017 5:55:47 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
* BuilderFlat generated by hbm2java
*/
@Entity
@Table(name = "builder_building_flat_type", catalog = "blue_pigeon")
public class BuilderBuildingFlatType implements java.io.Serializable {

	private Integer id;
	private BuilderFlatType builderFlatType;
	private BuilderBuilding builderBuilding;

	public BuilderBuildingFlatType() {
	}

	public BuilderBuildingFlatType(BuilderFlatType builderFlatType, BuilderBuilding builderBuilding) {
		this.builderFlatType = builderFlatType;
		this.builderBuilding = builderBuilding;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "flat_type_id")
	public BuilderFlatType getBuilderFlatType() {
		return this.builderFlatType;
	}

	public void setBuilderFlatType(BuilderFlatType builderFlatType) {
		this.builderFlatType = builderFlatType;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "building_id")
	public BuilderBuilding getBuilderBuilding() {
		return this.builderBuilding;
	}

	public void setBuilderBuilding(BuilderBuilding builderBuilding) {
		this.builderBuilding = builderBuilding;
	}

}
