package org.bluepigeon.admin.model;
// Generated 27 Mar, 2017 5:55:47 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BuilderProjectProjectType generated by hbm2java
 */
@Entity
@Table(name = "builder_project_project_type", catalog = "blue_pigeon")
public class BuilderProjectProjectType implements java.io.Serializable {

	private Integer id;
	private BuilderProjectType builderProjectType;
	private BuilderProject builderProject;

	public BuilderProjectProjectType() {
	}

	public BuilderProjectProjectType(BuilderProjectType builderProjectType, BuilderProject builderProject) {
		this.builderProjectType = builderProjectType;
		this.builderProject = builderProject;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project_type_id")
	public BuilderProjectType getBuilderProjectType() {
		return this.builderProjectType;
	}

	public void setBuilderProjectType(BuilderProjectType builderProjectType) {
		this.builderProjectType = builderProjectType;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project_id")
	public BuilderProject getBuilderProject() {
		return this.builderProject;
	}

	public void setBuilderProject(BuilderProject builderProject) {
		this.builderProject = builderProject;
	}

}
