package org.bluepigeon.admin.model;
// Generated 16 Mar, 2017 3:30:20 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BuilderProjectApprovalInfo generated by hbm2java
 */
@Entity
@Table(name = "builder_project_approval_info", catalog = "blue_pigeon")
public class BuilderProjectApprovalInfo implements java.io.Serializable {

	private Integer id;
	private BuilderProjectApprovalType builderProjectApprovalType;
	private BuilderProject builderProject;

	public BuilderProjectApprovalInfo() {
	}

	public BuilderProjectApprovalInfo(BuilderProjectApprovalType builderProjectApprovalType,
			BuilderProject builderProject) {
		this.builderProjectApprovalType = builderProjectApprovalType;
		this.builderProject = builderProject;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "approval_id")
	public BuilderProjectApprovalType getBuilderProjectApprovalType() {
		return this.builderProjectApprovalType;
	}

	public void setBuilderProjectApprovalType(BuilderProjectApprovalType builderProjectApprovalType) {
		this.builderProjectApprovalType = builderProjectApprovalType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public BuilderProject getBuilderProject() {
		return this.builderProject;
	}

	public void setBuilderProject(BuilderProject builderProject) {
		this.builderProject = builderProject;
	}

}
