package org.bluepigeon.admin.model;
// Generated 28 Mar, 2017 12:04:04 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BuildingPaymentInfo generated by hbm2java
 */
@Entity
@Table(name = "building_payment_info", catalog = "blue_pigeon")
public class BuildingPaymentInfo implements java.io.Serializable {

	private Integer id;
	private BuilderBuilding builderBuilding;
	private String milestone;
	private Double payable;
	private Double amount;
	private Byte status;

	public BuildingPaymentInfo() {
	}

	public BuildingPaymentInfo(BuilderBuilding builderBuilding, String milestone, Double payable, Double amount,
			Byte status) {
		this.builderBuilding = builderBuilding;
		this.milestone = milestone;
		this.payable = payable;
		this.amount = amount;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "building_id")
	public BuilderBuilding getBuilderBuilding() {
		return this.builderBuilding;
	}

	public void setBuilderBuilding(BuilderBuilding builderBuilding) {
		this.builderBuilding = builderBuilding;
	}

	@Column(name = "milestone", length = 128)
	public String getMilestone() {
		return this.milestone;
	}

	public void setMilestone(String milestone) {
		this.milestone = milestone;
	}

	@Column(name = "payable", precision = 22, scale = 0)
	public Double getPayable() {
		return this.payable;
	}

	public void setPayable(Double payable) {
		this.payable = payable;
	}

	@Column(name = "amount", precision = 22, scale = 0)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
