package org.bluepigeon.admin.model;
// Generated 28 Mar, 2017 12:04:04 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BuildingOfferInfo generated by hbm2java
 */
@Entity
@Table(name = "building_offer_info", catalog = "blue_pigeon")
public class BuildingOfferInfo implements java.io.Serializable {

	private Integer id;
	private BuilderBuilding builderBuilding;
	private String title;
	private Double per;
	private Double amount;
	private Double applicable;
	private Byte apply;

	public BuildingOfferInfo() {
	}

	public BuildingOfferInfo(BuilderBuilding builderBuilding, String title, Double per, Double amount,
			Double applicable, Byte apply) {
		this.builderBuilding = builderBuilding;
		this.title = title;
		this.per = per;
		this.amount = amount;
		this.applicable = applicable;
		this.apply = apply;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "building_id")
	public BuilderBuilding getBuilderBuilding() {
		return this.builderBuilding;
	}

	public void setBuilderBuilding(BuilderBuilding builderBuilding) {
		this.builderBuilding = builderBuilding;
	}

	@Column(name = "title", length = 128)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "per", precision = 22, scale = 0)
	public Double getPer() {
		return this.per;
	}

	public void setPer(Double per) {
		this.per = per;
	}

	@Column(name = "amount", precision = 22, scale = 0)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Column(name = "applicable", precision = 22, scale = 0)
	public Double getApplicable() {
		return this.applicable;
	}

	public void setApplicable(Double applicable) {
		this.applicable = applicable;
	}

	@Column(name = "apply")
	public Byte getApply() {
		return this.apply;
	}

	public void setApply(Byte apply) {
		this.apply = apply;
	}

}
