package org.bluepigeon.admin.model;
// Generated 16 Mar, 2017 3:30:20 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BuilderProjectPropertyType generated by hbm2java
 */
@Entity
@Table(name = "builder_project_property_type", catalog = "blue_pigeon")
public class BuilderProjectPropertyType implements java.io.Serializable {

	private Integer id;
	private BuilderPropertyType builderPropertyType;
	private BuilderProject builderProject;
	private Integer value;

	public BuilderProjectPropertyType() {
	}

	public BuilderProjectPropertyType(BuilderPropertyType builderPropertyType, BuilderProject builderProject,
			Integer value) {
		this.builderPropertyType = builderPropertyType;
		this.builderProject = builderProject;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "property_type_id")
	public BuilderPropertyType getBuilderPropertyType() {
		return this.builderPropertyType;
	}

	public void setBuilderPropertyType(BuilderPropertyType builderPropertyType) {
		this.builderPropertyType = builderPropertyType;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project_id")
	public BuilderProject getBuilderProject() {
		return this.builderProject;
	}

	public void setBuilderProject(BuilderProject builderProject) {
		this.builderProject = builderProject;
	}

	@Column(name = "value")
	public Integer getValue() {
		return this.value;
	}

	public void setValue(Integer value) {
		this.value = value;
	}

}
