package org.bluepigeon.admin.model;
// Generated 16 Mar, 2017 3:30:20 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BuilderProjectPropertyConfigurationInfo generated by hbm2java
 */
@Entity
@Table(name = "builder_project_property_configuration_info", catalog = "blue_pigeon")
public class BuilderProjectPropertyConfigurationInfo implements java.io.Serializable {

	private Integer id;
	private BuilderProjectPropertyConfiguration builderProjectPropertyConfiguration;
	private BuilderProject builderProject;
	private Integer value;

	public BuilderProjectPropertyConfigurationInfo() {
	}

	public BuilderProjectPropertyConfigurationInfo(
			BuilderProjectPropertyConfiguration builderProjectPropertyConfiguration, BuilderProject builderProject,
			Integer value) {
		this.builderProjectPropertyConfiguration = builderProjectPropertyConfiguration;
		this.builderProject = builderProject;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "property_config_id")
	public BuilderProjectPropertyConfiguration getBuilderProjectPropertyConfiguration() {
		return this.builderProjectPropertyConfiguration;
	}

	public void setBuilderProjectPropertyConfiguration(
			BuilderProjectPropertyConfiguration builderProjectPropertyConfiguration) {
		this.builderProjectPropertyConfiguration = builderProjectPropertyConfiguration;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public BuilderProject getBuilderProject() {
		return this.builderProject;
	}

	public void setBuilderProject(BuilderProject builderProject) {
		this.builderProject = builderProject;
	}

	@Column(name = "value")
	public Integer getValue() {
		return this.value;
	}

	public void setValue(Integer value) {
		this.value = value;
	}

}
