package org.bluepigeon.admin.model;
// Generated 27 Mar, 2017 5:55:47 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BuilderLead generated by hbm2java
 */
@Entity
@Table(name = "builder_lead", catalog = "blue_pigeon")
public class BuilderLead implements java.io.Serializable {

	private Integer id;
	private BuilderProject builderProject;
	private BuilderBuilding builderBuilding;
	private BuilderFlat builderFlat;
	private String city;
	private String name;
	private String mobile;
	private String email;
	private String area;
	private Integer source;
	private Integer addedBy;
	private String discountOffered;
	private Integer status;
	private Integer interestedIn;
	private BuilderPropertyType builderPropertyType;

	public BuilderLead() {
	}

	public BuilderLead(BuilderProject builderProject, BuilderBuilding builderBuilding,
			BuilderFlat builderFlat, String city, String name, String mobile, String email, String area, 
			Integer source, Integer addedBy, String discountOffered, Integer status,Integer interestedIn) {
		this.builderProject = builderProject;
		this.builderBuilding = builderBuilding;
		this.builderFlat = builderFlat;
		this.city = city;
		this.name = name;
		this.mobile = mobile;
		this.email = email;
		this.area = area;
		this.source = source;
		this.addedBy = addedBy;
		this.discountOffered = discountOffered;
		this.status = status;
		this.interestedIn = interestedIn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project_id")
	public BuilderProject getBuilderProject() {
		return builderProject;
	}

	public void setBuilderProject(BuilderProject builderProject) {
		this.builderProject = builderProject;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "building_id")
	public BuilderBuilding getBuilderBuilding() {
		return builderBuilding;
	}

	public void setBuilderBuilding(BuilderBuilding builderBuilding) {
		this.builderBuilding = builderBuilding;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "flat_id")
	public BuilderFlat getBuilderFlat() {
		return builderFlat;
	}

	public void setBuilderFlat(BuilderFlat builderFlat) {
		this.builderFlat = builderFlat;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "type_id")
	public BuilderPropertyType getBuilderPropertyType() {
		return builderPropertyType;
	}

	public void setBuilderPropertyType(BuilderPropertyType builderPropertyType) {
		this.builderPropertyType = builderPropertyType;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@Column(name = "city_id")
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "name", length = 128)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "mobile", length = 10)
	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "email", length = 128)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "area", length = 128)
	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "source")
	public Integer getSource() {
		return source;
	}

	public void setSource(Integer source) {
		this.source = source;
	}

	@Column(name = "added_by", length = 128)
	public Integer getAddedBy() {
		return addedBy;
	}

	public void setAddedBy(Integer addedBy) {
		this.addedBy = addedBy;
	}

	@Column(name = "discount_offered", length = 255)
	public String getDiscountOffered() {
		return discountOffered;
	}

	public void setDiscountOffered(String discountOffered) {
		this.discountOffered = discountOffered;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
	@Column(name = "interested_in")
	public Integer getInterestedIn() {
		return interestedIn;
	}

	public void setInterestedIn(Integer interestedIn) {
		this.interestedIn = interestedIn;
	}

	

}
