package org.bluepigeon.admin.model;
//Generated 27 Mar, 2017 5:55:47 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
* BuilderFlat generated by hbm2java
*/
@Entity
@Table(name = "builder_building_flat_type_room", catalog = "blue_pigeon")
public class BuilderBuildingFlatTypeRoom implements java.io.Serializable {

	private Integer id;
	private BuilderFlatType builderFlatType;
	private String roomName;
	private Double length;
	private Double breadth;
	private Byte lengthUnit;

	public BuilderBuildingFlatTypeRoom() {
	}

	public BuilderBuildingFlatTypeRoom(BuilderFlatType builderFlatType, String roomName, Double length, Double breadth, Byte lengthUnit) {
		this.builderFlatType = builderFlatType;
		this.roomName = roomName;
		this.length = length;
		this.breadth = breadth;
		this.lengthUnit = lengthUnit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "flat_type_id")
	public BuilderFlatType getBuilderFlatType() {
		return this.builderFlatType;
	}

	public void setBuilderFlatType(BuilderFlatType builderFlatType) {
		this.builderFlatType = builderFlatType;
	}

	@Column(name = "room_name", length = 128)
	public String getRoomName() {
		return this.roomName;
	}

	public void setRoomName(String name) {
		this.roomName = name;
	}
	
	@Column(name = "length")
	public Double getLength() {
		return this.length;
	}

	public void setLength(Double length) {
		this.length = length;
	}
	@Column(name = "breadth")
	public Double getBreadth() {
		return this.breadth;
	}

	public void setBreadth(Double breadth) {
		this.breadth = breadth;
	}
	
	@Column(name = "length_unit")
	public Byte getLengthUnit() {
		return this.lengthUnit;
	}

	public void setLengthUnit(Byte lengthUnit) {
		this.lengthUnit = lengthUnit;
	}


}
