package org.bluepigeon.admin.model;
// Generated 27 Mar, 2017 5:55:47 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BuilderBuildingAmenity generated by hbm2java
 */
@Entity
@Table(name = "builder_building_amenity", catalog = "blue_pigeon")
public class BuilderBuildingAmenity implements java.io.Serializable {

	private Integer id;
	private String name;
	private String iconUrl = "";
	private Byte status;
	private Byte isDeleted;
	private Set<BuilderBuildingAmenityStages> builderBuildingAmenityStageses = new HashSet<BuilderBuildingAmenityStages>(
			0);

	public BuilderBuildingAmenity() {
	}

	public BuilderBuildingAmenity(String name, Byte status, String iconUrl, Byte isDeleted,
			Set<BuilderBuildingAmenityStages> builderBuildingAmenityStageses) {
		this.name = name;
		this.iconUrl = iconUrl;
		this.status = status;
		this.isDeleted = isDeleted;
		this.builderBuildingAmenityStageses = builderBuildingAmenityStageses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "icon_url", length = 255)
	public String getIconUrl() {
		return iconUrl;
	}

	public void setIconUrl(String iconUrl) {
		this.iconUrl = iconUrl;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "is_deleted")
	public Byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "builderBuildingAmenity")
	public Set<BuilderBuildingAmenityStages> getBuilderBuildingAmenityStageses() {
		return this.builderBuildingAmenityStageses;
	}

	public void setBuilderBuildingAmenityStageses(Set<BuilderBuildingAmenityStages> builderBuildingAmenityStageses) {
		this.builderBuildingAmenityStageses = builderBuildingAmenityStageses;
	}

}
