package org.bluepigeon.admin.model;
// Generated 27 Mar, 2017 5:55:47 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BuilderLead generated by hbm2java
 */
@Entity
@Table(name = "builder_lead", catalog = "blue_pigeon")
public class BuilderLead implements java.io.Serializable {

	private Integer id;
	private BuilderSellerType builderSellerType;
	private AdminUser adminUser;
	private BuilderPropertyType builderPropertyType;
	private City city;
	private BuilderFlat builderFlat;
	private String name;
	private String mobile;
	private String email;
	private String area;
	private Byte status;

	public BuilderLead() {
	}

	public BuilderLead(BuilderSellerType builderSellerType, AdminUser adminUser,
			BuilderPropertyType builderPropertyType, City city, BuilderFlat builderFlat, String name, String mobile,
			String email, String area, Byte status) {
		this.builderSellerType = builderSellerType;
		this.adminUser = adminUser;
		this.builderPropertyType = builderPropertyType;
		this.city = city;
		this.builderFlat = builderFlat;
		this.name = name;
		this.mobile = mobile;
		this.email = email;
		this.area = area;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "seller_id")
	public BuilderSellerType getBuilderSellerType() {
		return this.builderSellerType;
	}

	public void setBuilderSellerType(BuilderSellerType builderSellerType) {
		this.builderSellerType = builderSellerType;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "source")
	public AdminUser getAdminUser() {
		return this.adminUser;
	}

	public void setAdminUser(AdminUser adminUser) {
		this.adminUser = adminUser;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "type")
	public BuilderPropertyType getBuilderPropertyType() {
		return this.builderPropertyType;
	}

	public void setBuilderPropertyType(BuilderPropertyType builderPropertyType) {
		this.builderPropertyType = builderPropertyType;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "city_id")
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "flat_id")
	public BuilderFlat getBuilderFlat() {
		return this.builderFlat;
	}

	public void setBuilderFlat(BuilderFlat builderFlat) {
		this.builderFlat = builderFlat;
	}

	@Column(name = "name", length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "mobile", length = 225)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "email", length = 225)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "area", length = 128)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
