package org.bluepigeon.admin.model;
// Generated 23 Mar, 2017 10:55:42 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BuilderProjectAmenityInfo generated by hbm2java
 */
@Entity
@Table(name = "builder_project_amenity_info", catalog = "blue_pigeon")
public class BuilderProjectAmenityInfo implements java.io.Serializable {

	private Integer id;
	private BuilderProjectAmenitySubstages builderProjectAmenitySubstages;
	private BuilderProject builderProject;

	public BuilderProjectAmenityInfo() {
	}

	public BuilderProjectAmenityInfo(BuilderProjectAmenitySubstages builderProjectAmenitySubstages,
			BuilderProject builderProject) {
		this.builderProjectAmenitySubstages = builderProjectAmenitySubstages;
		this.builderProject = builderProject;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "amenity_id")
	public BuilderProjectAmenitySubstages getBuilderProjectAmenitySubstages() {
		return this.builderProjectAmenitySubstages;
	}

	public void setBuilderProjectAmenitySubstages(BuilderProjectAmenitySubstages builderProjectAmenitySubstages) {
		this.builderProjectAmenitySubstages = builderProjectAmenitySubstages;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project_id")
	public BuilderProject getBuilderProject() {
		return this.builderProject;
	}

	public void setBuilderProject(BuilderProject builderProject) {
		this.builderProject = builderProject;
	}

}
