package org.bluepigeon.admin.model;
// Generated 28 Mar, 2017 12:04:04 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BuildingImageGallery generated by hbm2java
 */
@Entity
@Table(name = "building_image_gallery", catalog = "blue_pigeon")
public class BuildingImageGallery implements java.io.Serializable {

	private Integer id;
	private BuilderBuilding builderBuilding;
	private String image;
	private String title;

	public BuildingImageGallery() {
	}

	public BuildingImageGallery(BuilderBuilding builderBuilding, String image, String title) {
		this.builderBuilding = builderBuilding;
		this.image = image;
		this.title = title;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "building_id")
	public BuilderBuilding getBuilderBuilding() {
		return this.builderBuilding;
	}

	public void setBuilderBuilding(BuilderBuilding builderBuilding) {
		this.builderBuilding = builderBuilding;
	}

	@Column(name = "image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "title", length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
