package org.bluepigeon.admin.model;
// Generated 13 Apr, 2017 11:28:44 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CampaignBuyer generated by hbm2java
 */
@Entity
@Table(name = "campaign_buyer", catalog = "blue_pigeon")
public class CampaignBuyer implements java.io.Serializable {

	private Integer id;
	private Campaign campaign;
	private Buyer buyer;

	public CampaignBuyer() {
	}

	public CampaignBuyer(Campaign campaign, Buyer buyer) {
		this.campaign = campaign;
		this.buyer = buyer;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "campaign_id")
	public Campaign getCampaign() {
		return this.campaign;
	}

	public void setCampaign(Campaign campaign) {
		this.campaign = campaign;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "buyer_id")
	public Buyer getBuyer() {
		return this.buyer;
	}

	public void setBuyer(Buyer buyer) {
		this.buyer = buyer;
	}

}
