package org.bluepigeon.admin.model;
// Generated 13 Apr, 2017 11:28:44 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CampaignBuyer generated by hbm2java
 */
@Entity
@Table(name = "campaign_buyer", catalog = "blue_pigeon")
public class CampaignBuyer implements java.io.Serializable {

	private Integer id;
	private Campaign campaign;
	private Integer buyerId=0;
	private Integer userType=0;
	private Integer projectId=0;
	public CampaignBuyer() {
	}

	public CampaignBuyer(Campaign campaign, Integer buyerId, Integer userType, Integer projectId) {
		this.campaign = campaign;
		this.buyerId = buyerId;
		this.userType = userType;
		this.projectId = projectId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "campaign_id")
	public Campaign getCampaign() {
		return this.campaign;
	}

	public void setCampaign(Campaign campaign) {
		this.campaign = campaign;
	}

	@Column(name = "buyer_id")
	public Integer getBuyerId() {
		return this.buyerId;
	}

	public void setBuyerId(Integer buyerId) {
		this.buyerId = buyerId;
	}
	@Column(name= "user_type")
	public Integer getUserType() {
		return userType;
	}

	public void setUserType(Integer userType) {
		this.userType = userType;
	}
	@Column(name= "project_id")
	public Integer getProjectId() {
		return projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}
	
}
