package org.bluepigeon.admin.model;
// Generated 7 Apr, 2017 4:51:30 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DemandLettersInfo generated by hbm2java
 */
@Entity
@Table(name = "demand_letters_info", catalog = "blue_pigeon")
public class DemandLettersInfo implements java.io.Serializable {

	private Integer id;
	private DemandLetters demandLetters;
	private String docUrl;

	public DemandLettersInfo() {
	}

	public DemandLettersInfo(DemandLetters demandLetters, String docUrl) {
		this.demandLetters = demandLetters;
		this.docUrl = docUrl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "demand_id")
	public DemandLetters getDemandLetters() {
		return this.demandLetters;
	}

	public void setDemandLetters(DemandLetters demandLetters) {
		this.demandLetters = demandLetters;
	}

	@Column(name = "doc_url", length = 225)
	public String getDocUrl() {
		return this.docUrl;
	}

	public void setDocUrl(String docUrl) {
		this.docUrl = docUrl;
	}

}
