package org.bluepigeon.admin.model;
//Generated 28 Mar, 2017 12:04:04 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
* BuildingAmenityInfo generated by hbm2java
*/
@Entity
@Table(name = "flat_amenity_info", catalog = "blue_pigeon")
public class FlatAmenityInfo implements java.io.Serializable {

	private Integer id;
	private BuilderFlat builderFlat;
	private BuilderFlatAmenity builderFlatAmenity;

	public FlatAmenityInfo() {
	}

	public FlatAmenityInfo(BuilderFlat builderFlat, BuilderFlatAmenity builderFlatAmenity) {
		this.builderFlat = builderFlat;
		this.builderFlatAmenity = builderFlatAmenity;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "flat_id")
	public BuilderFlat getBuilderFlat() {
		return this.builderFlat;
	}

	public void setBuilderFlat(BuilderFlat builderFlat) {
		this.builderFlat = builderFlat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "amenity_id")
	public BuilderFlatAmenity getBuilderFlatAmenity() {
		return this.builderFlatAmenity;
	}

	public void setBuilderFlatAmenity(BuilderFlatAmenity builderFlatAmenity) {
		this.builderFlatAmenity = builderFlatAmenity;
	}

}

