package org.bluepigeon.admin.model;
// Generated 16 May, 2017 11:21:31 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FlatStage generated by hbm2java
 */
@Entity
@Table(name = "flat_stage", catalog = "blue_pigeon")
public class FlatStage implements java.io.Serializable {

	private Integer id;
	private String name;
	private Byte status;
	private Byte isDeleted=0;
	private Set<FlatSubstage> flatSubstages = new HashSet<FlatSubstage>(0);

	public FlatStage() {
	}

	public FlatStage(String name, Byte status, Byte isDeleted, Set<FlatSubstage> flatSubstages) {
		this.name = name;
		this.status = status;
		this.isDeleted = isDeleted;
		this.flatSubstages = flatSubstages;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "is_deleted")
	public Byte getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Byte isDeleted) {
		this.isDeleted = isDeleted;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "flatStage")
	public Set<FlatSubstage> getFlatSubstages() {
		return this.flatSubstages;
	}

	public void setFlatSubstages(Set<FlatSubstage> flatSubstages) {
		this.flatSubstages = flatSubstages;
	}

}
