package org.bluepigeon.admin.model;
// Generated 31 Mar, 2017 11:32:34 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FloorImageGallery generated by hbm2java
 */
@Entity
@Table(name = "flat_image_gallery", catalog = "blue_pigeon")
public class FlatImageGallery implements java.io.Serializable {

	private Integer id;
	private BuilderFlat builderFlat;
	private String image;

	public FlatImageGallery() {
	}

	public FlatImageGallery(BuilderFlat builderFlat, String image) {
		this.builderFlat = builderFlat;
		this.image = image;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "flat_id")
	public BuilderFlat getBuilderFlat() {
		return this.builderFlat;
	}

	public void setBuilderFlat(BuilderFlat builderFlat) {
		this.builderFlat = builderFlat;
	}

	@Column(name = "image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

}
