package org.bluepigeon.admin.model;
// Generated 31 Mar, 2017 11:32:34 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FloorPanoramicImage generated by hbm2java
 */
@Entity
@Table(name = "floor_panoramic_image", catalog = "blue_pigeon")
public class FloorPanoramicImage implements java.io.Serializable {

	private Integer id;
	private BuilderFloor builderFloor;
	private String panoImage;

	public FloorPanoramicImage() {
	}

	public FloorPanoramicImage(BuilderFloor builderFloor, String panoImage) {
		this.builderFloor = builderFloor;
		this.panoImage = panoImage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "floor_id")
	public BuilderFloor getBuilderFloor() {
		return this.builderFloor;
	}

	public void setBuilderFloor(BuilderFloor builderFloor) {
		this.builderFloor = builderFloor;
	}

	@Column(name = "pano_image", length = 45)
	public String getPanoImage() {
		return this.panoImage;
	}

	public void setPanoImage(String panoImage) {
		this.panoImage = panoImage;
	}

}
