package org.bluepigeon.admin.model;
// Generated 21 Apr, 2017 5:15:25 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ManageProjects generated by hbm2java
 */
@Entity
@Table(name = "manage_projects", catalog = "blue_pigeon")
public class ManageProjects implements java.io.Serializable {

	private Integer id;
	private BuilderProject builderProject;
	private PropertyManager propertyManager;

	public ManageProjects() {
	}

	public ManageProjects(BuilderProject builderProject, PropertyManager propertyManager) {
		this.builderProject = builderProject;
		this.propertyManager = propertyManager;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project_id")
	public BuilderProject getBuilderProject() {
		return this.builderProject;
	}

	public void setBuilderProject(BuilderProject builderProject) {
		this.builderProject = builderProject;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "manager_id")
	public PropertyManager getPropertyManager() {
		return this.propertyManager;
	}

	public void setPropertyManager(PropertyManager propertyManager) {
		this.propertyManager = propertyManager;
	}

}
