package org.bluepigeon.admin.model;
// Generated 12 May, 2017 3:18:30 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PossessionBuyer generated by hbm2java
 */
@Entity
@Table(name = "possession_buyer", catalog = "blue_pigeon")
public class PossessionBuyer implements java.io.Serializable {

	private Integer id;
	private Possession possession;
	private Buyer buyer;

	public PossessionBuyer() {
	}

	public PossessionBuyer(Possession possession, Buyer buyer) {
		this.possession = possession;
		this.buyer = buyer;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "possession_id", nullable = false)
	public Possession getPossession() {
		return this.possession;
	}

	public void setPossession(Possession possession) {
		this.possession = possession;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "buyer_id", nullable = false)
	public Buyer getBuyer() {
		return this.buyer;
	}

	public void setBuyer(Buyer buyer) {
		this.buyer = buyer;
	}

}
