package org.bluepigeon.admin.model;
// Generated 27 Mar, 2017 5:55:47 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProjectPanoramicImage generated by hbm2java
 */
@Entity
@Table(name = "project_panoramic_image", catalog = "blue_pigeon")
public class ProjectPanoramicImage implements java.io.Serializable {

	private Integer id;
	private BuilderProject builderProject;
	private String title;
	private String panoImage;

	public ProjectPanoramicImage() {
	}

	public ProjectPanoramicImage(BuilderProject builderProject, String title, String panoImage) {
		this.builderProject = builderProject;
		this.title = title;
		this.panoImage = panoImage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project_id")
	public BuilderProject getBuilderProject() {
		return this.builderProject;
	}

	public void setBuilderProject(BuilderProject builderProject) {
		this.builderProject = builderProject;
	}

	@Column(name = "title", length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "pano_image", length = 128)
	public String getPanoImage() {
		return this.panoImage;
	}

	public void setPanoImage(String panoImage) {
		this.panoImage = panoImage;
	}

}
