//package org.bluepigeon.admin.model;
//// Generated 21 Apr, 2017 5:15:25 PM by Hibernate Tools 4.0.0
//
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import static javax.persistence.GenerationType.IDENTITY;
//import javax.persistence.Id;
//import javax.persistence.JoinColumn;
//import javax.persistence.ManyToOne;
//import javax.persistence.Table;
//
///**
// * PropertyManagerPhotos generated by hbm2java
// */
//@Entity
//@Table(name = "property_manager_photos", catalog = "blue_pigeon")
//public class PropertyManagerPhotos implements java.io.Serializable {
//
//	private Integer id;
//	private PropertyManager propertyManager;
//	private String photoUrl;
//
//	public PropertyManagerPhotos() {
//	}
//
//	public PropertyManagerPhotos(PropertyManager propertyManager, String photoUrl) {
//		this.propertyManager = propertyManager;
//		this.photoUrl = photoUrl;
//	}
//
//	@Id
//	@GeneratedValue(strategy = IDENTITY)
//
//	@Column(name = "id", unique = true, nullable = false)
//	public Integer getId() {
//		return this.id;
//	}
//
//	public void setId(Integer id) {
//		this.id = id;
//	}
//
//	@ManyToOne(fetch = FetchType.EAGER)
//	@JoinColumn(name = "manager_id")
//	public PropertyManager getPropertyManager() {
//		return this.propertyManager;
//	}
//
//	public void setPropertyManager(PropertyManager propertyManager) {
//		this.propertyManager = propertyManager;
//	}
//
//	@Column(name = "photo_url", length = 45)
//	public String getPhotoUrl() {
//		return this.photoUrl;
//	}
//
//	public void setPhotoUrl(String photoUrl) {
//		this.photoUrl = photoUrl;
//	}
//
//}
